/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.form;

import com.jtattoo.plaf.aluminium.AluminiumLookAndFeel;
import com.jtattoo.plaf.hifi.HiFiLookAndFeel;
import com.jtattoo.plaf.mint.MintLookAndFeel;
import fileMp3.FileMp3;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import playList.PlayList;

/**
 *
 * @author rustam
 */
public class PleerOnSwingxForm extends javax.swing.JFrame {

    /**
     * Creates new form PleerOnSwingxForm
     */
    public PleerOnSwingxForm() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonSearch = new javax.swing.JButton();
        jTextFieldSearch = new javax.swing.JTextField();
        jPanelMain = new javax.swing.JPanel();
        jButtonPreviousSong = new javax.swing.JButton();
        jButtonPause = new javax.swing.JButton();
        jButtonPlay = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();
        jButtonStop = new javax.swing.JButton();
        jSliderVolume = new javax.swing.JSlider();
        jToggleButtonV = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButtonAddSong = new javax.swing.JButton();
        jButtonDeleteSong = new javax.swing.JButton();
        jButtonScrollDown = new javax.swing.JButton();
        jButtonScrollUp = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuOpenPlayList = new javax.swing.JMenuItem();
        jMenuSavePlaylist = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuExit = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuChangeSkin = new javax.swing.JMenu();
        jSubMenuChangeSkin1 = new javax.swing.JMenuItem();
        jSubMenuChangeSkin2 = new javax.swing.JMenuItem();
        jSubMenuChangeSkin3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pressedKeySkin1(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPleer/search_16.png"))); // NOI18N
        jButtonSearch.setText("Search");
        jButtonSearch.setToolTipText("Search treck");

        jTextFieldSearch.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jTextFieldSearch.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldSearch.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldSearch.setText("insert name of song");
        jTextFieldSearch.setSelectedTextColor(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSearch)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(101, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jTextFieldSearch)
                    .addGap(10, 10, 10)))
        );

        jPanelMain.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonPreviousSong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPleer/prev-icon.png"))); // NOI18N
        jButtonPreviousSong.setToolTipText("Previous track");

        jButtonPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPleer/Pause-icon.png"))); // NOI18N
        jButtonPause.setToolTipText("Pause");

        jButtonPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPleer/Play.png"))); // NOI18N
        jButtonPlay.setToolTipText("Play music");

        jButtonNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPleer/next-icon.png"))); // NOI18N
        jButtonNext.setToolTipText("Next track");

        jButtonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPleer/stop-red-icon.png"))); // NOI18N
        jButtonStop.setToolTipText("Stop");

        jToggleButtonV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPleer/speaker.png"))); // NOI18N
        jToggleButtonV.setToolTipText("Mute");
        jToggleButtonV.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPleer/mute.png"))); // NOI18N
        jToggleButtonV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonVActionPerformed(evt);
            }
        });

        jScrollPane1.setToolTipText("playlist");

        jList1.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "song 1", "song 2", "song 3", "song 4", "song 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jButtonAddSong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPleer/plus_16.png"))); // NOI18N
        jButtonAddSong.setToolTipText("Add new track");

        jButtonDeleteSong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPleer/remove_icon.png"))); // NOI18N
        jButtonDeleteSong.setToolTipText("Remove selected track");

        jButtonScrollDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPleer/arrow-down-icon.png"))); // NOI18N
        jButtonScrollDown.setToolTipText("Scroll down");

        jButtonScrollUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPleer/arrow-up-icon.png"))); // NOI18N
        jButtonScrollUp.setToolTipText("Scroll up");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jToggleButtonV, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderVolume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButtonPreviousSong, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonPause, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonStop, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButtonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 36, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonAddSong, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDeleteSong, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jButtonScrollDown, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonScrollUp, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddSong, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeleteSong, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonScrollDown, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonScrollUp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToggleButtonV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSliderVolume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPause, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonStop, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPreviousSong, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jMenuFile.setText("File");

        jMenuOpenPlayList.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.META_MASK));
        jMenuOpenPlayList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPleer/open-icon.png"))); // NOI18N
        jMenuOpenPlayList.setText("Open playlist");
        jMenuOpenPlayList.setToolTipText("Open new playlist");
        jMenuFile.add(jMenuOpenPlayList);

        jMenuSavePlaylist.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.META_MASK));
        jMenuSavePlaylist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPleer/save_16.png"))); // NOI18N
        jMenuSavePlaylist.setText("Save playlist");
        jMenuSavePlaylist.setToolTipText("Save current playlist");
        jMenuFile.add(jMenuSavePlaylist);
        jMenuFile.add(jSeparator1);

        jMenuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.META_MASK));
        jMenuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPleer/exit.png"))); // NOI18N
        jMenuExit.setText("Exit");
        jMenuExit.setToolTipText("Quit");
        jMenuFile.add(jMenuExit);

        jMenuBar.add(jMenuFile);

        jMenuEdit.setText("Edit");

        jMenuChangeSkin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPleer/gear_16.png"))); // NOI18N
        jMenuChangeSkin.setText("skins");

        jSubMenuChangeSkin1.setText("skin 1");
        jSubMenuChangeSkin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubMenuChangeSkin1Pressed(evt);
            }
        });
        jMenuChangeSkin.add(jSubMenuChangeSkin1);

        jSubMenuChangeSkin2.setText("skin 2");
        jSubMenuChangeSkin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubMenuChangeSkin2Pressed(evt);
            }
        });
        jMenuChangeSkin.add(jSubMenuChangeSkin2);

        jSubMenuChangeSkin3.setText("skin 3");
        jSubMenuChangeSkin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubMenuChangeSkin3Pressed(evt);
            }
        });
        jMenuChangeSkin.add(jSubMenuChangeSkin3);

        jMenuEdit.add(jMenuChangeSkin);

        jMenuBar.add(jMenuEdit);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonVActionPerformed

    private void pressedKeySkin1(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pressedKeySkin1
        // TODO add your handling code here:
    }//GEN-LAST:event_pressedKeySkin1

    private void jSubMenuChangeSkin1Pressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubMenuChangeSkin1Pressed
        try {
            UIManager.setLookAndFeel(new AluminiumLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(PleerOnSwingxForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_jSubMenuChangeSkin1Pressed

    private void jSubMenuChangeSkin2Pressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubMenuChangeSkin2Pressed
        try {
            UIManager.setLookAndFeel(new HiFiLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(PleerOnSwingxForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_jSubMenuChangeSkin2Pressed

    private void jSubMenuChangeSkin3Pressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubMenuChangeSkin3Pressed
        try {
            UIManager.setLookAndFeel(new MintLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(PleerOnSwingxForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_jSubMenuChangeSkin3Pressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            
            UIManager.setLookAndFeel(new MintLookAndFeel());
            //</editor-fold>
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(PleerOnSwingxForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PleerOnSwingxForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddSong;
    private javax.swing.JButton jButtonDeleteSong;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPause;
    private javax.swing.JButton jButtonPlay;
    private javax.swing.JButton jButtonPreviousSong;
    private javax.swing.JButton jButtonScrollDown;
    private javax.swing.JButton jButtonScrollUp;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonStop;
    private javax.swing.JList jList1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuChangeSkin;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenuItem jMenuExit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuOpenPlayList;
    private javax.swing.JMenuItem jMenuSavePlaylist;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSlider jSliderVolume;
    private javax.swing.JMenuItem jSubMenuChangeSkin1;
    private javax.swing.JMenuItem jSubMenuChangeSkin2;
    private javax.swing.JMenuItem jSubMenuChangeSkin3;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JToggleButton jToggleButtonV;
    // End of variables declaration//GEN-END:variables
}
